name: Update Stars

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual trigger
  watch:
    types: [started]  # Run when you star your own repository

permissions:
  contents: write
  issues: write

jobs:
  update-stars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper versioning
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Clean install dependencies
        run: |
          rm -rf node_modules
          npm install
          npm install --package-lock-only
          
      - name: Build TypeScript
        run: |
          npm run clean
          npm run build
          
      - name: Update STARRED.md
        run: npm start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
      
      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push if changed
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add STARRED.md package-lock.json
          git commit -m "Update starred repositories and dependencies [skip ci]"
          git push
