name: Update Stars

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual trigger
  watch:
    types: [started]  # Run when you star your own repository

permissions:
  contents: write
  issues: write

env:
  NODE_ENV: development
  DEBUG: '*'
  LOG_LEVEL: debug

jobs:
  update-stars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper versioning
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json
          
      - name: Clean install dependencies
        run: |
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          npm clean-install
          
      - name: Build TypeScript
        run: |
          npm run clean
          NODE_ENV=development npm run build
          echo "Build output files:"
          ls -la dist/
          
      - name: Update STARRED.md
        run: |
          echo "GitHub Token exists: ${{ secrets.GITHUB_TOKEN != '' }}"
          echo "GitHub Username: ${{ github.repository_owner }}"
          echo "Starting update process..."
          node --trace-warnings dist/update-stars.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
          NODE_ENV: development
          DEBUG: '*'
          LOG_LEVEL: debug
      
      - name: Check STARRED.md
        id: check_content
        run: |
          echo "Current directory contents:"
          ls -la
          if [ -f STARRED.md ]; then
            echo "STARRED.md exists"
            echo "File size: $(stat -f%z STARRED.md)"
            echo "Last few lines:"
            tail -n 5 STARRED.md
          else
            echo "STARRED.md does not exist"
          fi
      
      - name: Check for changes
        id: changes
        run: |
          if git status --porcelain | grep -q 'STARRED.md'; then
            echo "changes=true" >> "$GITHUB_OUTPUT"
            echo "Changes detected in STARRED.md"
            git diff STARRED.md
          else
            echo "changes=false" >> "$GITHUB_OUTPUT"
            echo "No changes detected in STARRED.md"
          fi

      - name: Commit and push if changed
        if: steps.changes.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add STARRED.md
          git commit -m "Update starred repositories [skip ci]"
          git push
        
      - name: Create issue on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Workflow failed: Update Stars',
              body: `The Update Stars workflow failed. Please check the [workflow run](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}) for details.
              
              Error occurred at: ${new Date().toISOString()}`
            });